stomatology/apps/card/urls.py
from django.urls import path
from . import views

app_name = 'card'

urlpatterns = [
    path('<int:id>',views.index, name='index'),
    path('print_info/<int:id>',views.print_info, name='print_info')
]

stomatology/apps/patients/urls.py
from django.urls import path
from . import views

app_name = 'patients'

urlpatterns = [
    path('',views.index, name='index'),
    path('add/',views.add, name='add'),
    path('reg/',views.reg, name='reg'),
    path('update/<int:id>',views.update, name='update'),
    path('delete/<int:id>',views.delete, name='delete')
]

stomatology/apps/stage1/urls.py
from django.urls import path
from . import views

app_name = 'stage1'

urlpatterns = [
    path('<int:id>',views.index, name='index'),
    path('update/<int:id>',views.update, name='update'),
    path('print_info/<int:id>',views.print_info, name='print_info')
]

stomatology/apps/stage2/urls.py
from django.urls import path
from . import views

app_name = 'stage2'

urlpatterns = [
    path('<int:id>', views.index, name='index'),
    path('update/<int:id>', views.update, name='update'),
    path('print_info/<int:id>',views.print_info, name='print_info')
]

stomatology/apps/stage3/urls.py
from django.urls import path
from . import views

app_name = 'stage3'

urlpatterns = [
    path('<int:id>', views.index, name='index'),
    path('update/<int:id>', views.update, name='update'),
    path('print_info/<int:id>',views.print_info, name='print_info')
]

stomatology/apps/stage4/urls.py
from django.urls import path
from . import views

app_name = 'stage4'

urlpatterns = [
    path('<int:id>',views.index, name='index'),
    path('update/<int:id>', views.update, name='update'),
    path('print_info/<int:id>',views.print_info, name='print_info')
]

stomatology/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('authorize.urls')),
    path('analysis/', include('analysis.urls')),
    path('materials/', include('materials.urls')),
    path('patients/', include('patients.urls')),
    path('timetable/', include('timetable.urls')),
    path('stage1/', include('stage1.urls')),
    path('stage2/', include('stage2.urls')),
    path('stage3/', include('stage3.urls')),
    path('stage4/', include('stage4.urls')),
    path('card/', include('card.urls')),
    path('admin/', admin.site.urls),
]

stomatology/apps/analysis/models.py
from django.db import models

# Create your models here.

stomatology/apps/authorize/models.py
from django.db import models
from django.contrib.auth.models import User


class Doctors(models.Model):
    def fio(self):
        return f'{self.user.last_name} {self.user.first_name}'
    user= models.ForeignKey(User, on_delete=models.CASCADE)
    position = models.CharField(max_length=100)

stomatology/apps/card/models.py
from django.db import models
from patients.models import Clients
from materials.models import *



class PatientCard(models.Model):
    client = models.OneToOneField(Clients, on_delete=models.CASCADE)
    status = models.CharField(max_length=100)


class Prosthesis(models.Model):
    card = models.OneToOneField(PatientCard, on_delete=models.CASCADE)
    type = models.ForeignKey(Type_prost, on_delete=models.CASCADE, null=True)
    construction = models.ForeignKey(Construction, on_delete=models.CASCADE, null=True)
    material = models.ForeignKey(Materials, on_delete=models.CASCADE, null=True)

stomatology/apps/analysis/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'analysis/index.html')

stomatology/apps/authorize/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect

def index(request):
    return render(request, 'base.html')

def log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('authorize:index'))


def reg(request):
    UserModel = get_user_model()
    user = UserModel.objects.create_user(request.POST['username'], request.POST['email'], request.POST['password'])
    user.first_name = request.POST['first_name']
    user.last_name = request.POST['last_name']
    user.save()
    """ client= Client.objects.create(user=user,email=request.POST['email'],
                                  first_name=request.POST['first_name'],
                                  last_name=request.POST['last_name'])
    client.save() """
    return HttpResponseRedirect(reverse('accounts:index'))


def log(request):
    user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
    if user is not None:
        login(request, user)
        return HttpResponseRedirect(reverse('authorize:index'))
    else: 
        return HttpResponseRedirect(reverse('authorize/signin'))


def getusers(request):
    a = User.objects.all()
    return render(request, 'registration/users.html', {'users': a})


def signup(request):
    return render(request, 'signup.html')


def signin(request):
    return render(request, 'authorize/login.html')

stomatology/apps/card/views.py
from django.shortcuts import render
from django.urls import reverse
from .models import *
from patients.models import *
from materials.models import *
from django.http import HttpResponseRedirect
import time
import os

def index(request,id):
    client = Clients.objects.get(id=id)
    card=PatientCard.objects.get(client=client)
    prothesis=Prosthesis.objects.get(card=card)
    a = Materials.objects.all()
    b = Type_prost.objects.all()
    c = Construction.objects.all()
    config = {
        'client': client,
        'materials': a,
        'types': b,
        'constructions': c,
        'prothesis':prothesis
    }
    return render(request, 'card/index.html',config)


def print_info(request,id):
    file=str(time.time())
    try:
        client = Clients.objects.get(id=id)
        print(client)
        card = PatientCard.objects.get(client=client)
        print(card)
        prothesis = Prosthesis.objects.get(card=card)
        print(prothesis)
        text_file = open(rf"c:\\prints\{file}.txt", "w")
        n = text_file.write(f'Прізвище:{ client.user.last_name }\n'
                            f'Ім\'я:{ client.user.first_name }\n'
                            f'Телефон:{ client.phone }\n'
                            f'Дата народження:{client.date_birth}\n'
                            f'Тип протезування:{client.patientcard.prosthesis.type.name}\n'
                            f'Конструкція:{client.patientcard.prosthesis.construction.name}\n'
                            f'Матеріал:{client.patientcard.prosthesis.material.name}\n'
                            f'Стать:{client.gender}\n'
                            f'Етапи лікування\n'
                            f'Етап 1/{prothesis.stages_1.date_record}:{prothesis.stages_1.conclusion}\n'
                            f'Етап 2/{prothesis.stages_2.date_record}:{prothesis.stages_2.conclusion}\n'
                            f'Етап 3/{prothesis.stages_3.date_record}:{prothesis.stages_3.conclusion}\n'
                            f'Етап 4/{prothesis.stages_4.date_record}:{prothesis.stages_4.conclusion}\n')

        print(n)
        text_file.close()
        file_path = rf'C:\\prints\{file}.txt'
        os.system("start " + file_path)
    except:
        text_file.close() 
    return HttpResponseRedirect(reverse('card:index', kwargs={'id': id}))

stomatology/apps/materials/views.py
from django.shortcuts import render
from django.urls import reverse
from .models import *
from django.http import HttpResponseRedirect


def index(request):
    a = Materials.objects.all()
    config = {
        'materials': a
    }
    return render(request, 'materials/index.html',config)\


def add(request):
    return render(request, 'materials/add.html')

def reg(request):
    material= Materials.objects.create(code=request.POST['code'],
                                   producer=request.POST['producer'],
                                  name=request.POST['name'],
                                  availability=request.POST['availability'],
                                  quality=request.POST['quality']
                                   )
    material.save()
    return HttpResponseRedirect(reverse('materials:index'))

def upd(request,id):
    material=Materials.objects.get(id=id)
    config={
        'material': material
    }
    return render(request, 'materials/update.html',config)
def update(request,id):
    material = Materials.objects.get(id=id)
    material.code = request.POST['code']
    material.producer = request.POST['producer']
    material.name = request.POST['name']
    material.availability = request.POST['availability']
    material.quality = request.POST['quality']
    material.save()
    return HttpResponseRedirect(reverse('materials:index'))

def delete(request, id):
    Materials.objects.get(id=id).delete()
    return HttpResponseRedirect(reverse('materials:index'))

stomatology/apps/patients/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from .models import *
from materials.models import *
from card.models import *
from stage1.models import *
from stage2.models import *
from stage3.models import *
from stage4.models import *
from datetime import date



def index(request):
    a = Clients.objects.all()
    config = {
        'clients': a
    }
    return render(request, 'patients/index.html',config)
def add(request):
    a = Materials.objects.all()
    b = Type_prost.objects.all()
    c = Construction.objects.all()
    config = {
        'materials': a,
        'types': b,
        'constructions': c
    }
    return render(request, 'patients/add.html',config)

def reg(request):
    UserModel = get_user_model()
    user = UserModel.objects.create_user(username=(request.POST['first_name']+request.POST['last_name']+request.POST['phone']), password='root')
    user.first_name = request.POST['first_name']
    user.last_name = request.POST['last_name']
    user.save()

    client= Clients.objects.create(user=user,phone=request.POST['phone'],
                                  gender=request.POST['gender'],
                                  date_birth=request.POST['date_birth'],
                                   middle_name = request.POST['middle_name'])
    client.save()
    patientcard = PatientCard.objects.create(client=client)
    patientcard.status = 'Новий пацієнт'
    patientcard.save()

    prosthesis = Prosthesis.objects.create(card=patientcard)
    prosthesis.type = Type_prost.objects.get(id=request.POST['type'])
    prosthesis.material = Materials.objects.get(id=request.POST['material'])
    prosthesis.construction = Construction.objects.get(id=request.POST['construction'])
    prosthesis.save()
    stage1=Stages_1.objects.create(prosthesis=prosthesis)
    stage1.save()
    stage2 = Stages_2.objects.create(prosthesis=prosthesis)
    stage2.save()
    stage3 = Stages_3.objects.create(prosthesis=prosthesis)
    stage3.save()
    stage4 = Stages_4.objects.create(prosthesis=prosthesis)
    stage4.save()
    return HttpResponseRedirect(reverse('patients:index'))


def update(request,id):
    client = Clients.objects.get(id=id)
    user = client.user
    user.last_name = request.POST['last_name']
    user.first_name = request.POST['first_name']
    user.save()
    client.phone = request.POST['phone']
    client.gender = request.POST['gender']
    client.middle_name = request.POST['middle_name']
    client.date_birth = request.POST['date_birth']
    prosthesis=client.patientcard.prosthesis
    prosthesis.material= Materials.objects.get(id=request.POST['material'])
    prosthesis.type = Type_prost.objects.get(id=request.POST['type'])
    prosthesis.construction = Construction.objects.get(id=request.POST['construction'])
    client.save()
    prosthesis.save()
    return HttpResponseRedirect(reverse('patients:index'))

def delete(request, id):
    Clients.objects.get(id=id).delete()
    return HttpResponseRedirect(reverse('patients:index'))

stomatology/apps/stage1/views.py
from django.shortcuts import render
from django.urls import reverse
from .models import *
from card.models import *
from patients.models import *
from django.http import HttpResponseRedirect
from materials.models import *
from datetime import date
import time
import os


def index(request,id):
    client = Clients.objects.get(id=id)
    a = Materials.objects.all()
    b = Type_prost.objects.all()
    c = Construction.objects.all()
    config = {
        'client': client,
        'materials': a,
        'types': b,
        'constructions': c
    }
    return render(request, 'stage1/index.html',config)
def update(request,id):
    client = Clients.objects.get(id=id)
    card=PatientCard.objects.get(client=client)
    card.status='Етап 1'
    card.save()
    stage=Stages_1.objects.get(id=client.patientcard.prosthesis.stages_1.id)
    if stage:
        stage.complaints =request.POST['complaints']
        stage.diagnosis =request.POST['diagnosis']
        stage.disease_current =request.POST['disease_current']
        stage.progress_disease =request.POST['progress_disease']
        stage.review =request.POST['review']
        stage.bite =request.POST['bite']
        stage.color =request.POST['color']
        stage.conclusion =request.POST['conclusion']
        stage.date_record = date.today()
        stage.save()
    return HttpResponseRedirect(reverse('stage1:index', kwargs={'id': id}))


def print_info(request,id):
    file = str(time.time())

    try:
        client = Clients.objects.get(id=id)
        text_file = open(rf"c:\\prints\{file}.txt", "w")
        n = text_file.write(f'Прізвище:{ client.user.last_name }\n'
                            f'Ім\'я:{ client.user.first_name }\n'
                            f'Телефон:{ client.phone }\n'
                            f'Дата народження:{client.date_birth}\n'
                            f'Тип протезування:{client.patientcard.prosthesis.type.name}\n'
                            f'Конструкція:{client.patientcard.prosthesis.construction.name}\n'
                            f'Матеріал:{client.patientcard.prosthesis.material.name}\n'
                            f'Стать:{client.gender}\n'
                            f'Етап 1 - Первичний огляд та визначення плану\n'
                            f'Скарги:{client.patientcard.prosthesis.stages_1.complaints}\n'
                            f'Діагноз:{client.patientcard.prosthesis.stages_1.diagnosis}\n'
                            f'Перенесені та супутні захворювання:{ client.patientcard.prosthesis.stages_1.disease_current }\n'
                            f'Розвиток захворювання:{ client.patientcard.prosthesis.stages_1.progress_disease }\n'
                            f'Дані об\'єктивного дослідження:{ client.patientcard.prosthesis.stages_1.review }\n'
                            f'Прикус:{ client.patientcard.prosthesis.stages_1.bite }\n'
                            f'Колір за шкалою \'Віта\':{ client.patientcard.prosthesis.stages_1.color }\n'
                            f'Висновок:{ client.patientcard.prosthesis.stages_1.conclusion }')
        text_file.close()
        file_path = rf"c:\\prints\{file}.txt"
        os.system("start " + file_path)

    except:
        text_file.close()
    return HttpResponseRedirect(reverse('stage1:index', kwargs={'id': id}))

stomatology/apps/stage2/views.py
from django.shortcuts import render
from django.urls import reverse
from .models import *
from patients.models import *
from django.http import HttpResponseRedirect
from materials.models import *
from datetime import date
from card.models import *
import time
import os

def index(request,id):
    client = Clients.objects.get(id=id)
    a = Materials.objects.all()
    b = Type_prost.objects.all()
    c = Construction.objects.all()
    config = {
        'client': client,
        'materials': a,
        'types': b,
        'constructions': c
    }
    return render(request, 'stage2/index.html',config)


def update(request,id):
    client = Clients.objects.get(id=id)
    card = PatientCard.objects.get(client=client)
    card.status = 'Етап 2'
    card.save()
    stage=Stages_2.objects.get(id=client.patientcard.prosthesis.stages_2.id)
    if stage:
        stage.conclusion = request.POST['conclusion']
        stage.date_record = date.today()
        stage.save()
    return HttpResponseRedirect(reverse('stage2:index', kwargs={'id': id}))


def print_info(request,id):
    file = str(time.time())
    try:
        client = Clients.objects.get(id=id)
        text_file = open(rf"c:\\prints\{file}.txt", "w")
        n = text_file.write(f'Прізвище:{ client.user.last_name }\n'
                            f'Ім\'я:{ client.user.first_name }\n'
                            f'Телефон:{ client.phone }\n'
                            f'Дата народження:{client.date_birth}\n'
                            f'Тип протезування:{client.patientcard.prosthesis.type.name}\n'
                            f'Конструкція:{client.patientcard.prosthesis.construction.name}\n'
                            f'Матеріал:{client.patientcard.prosthesis.material.name}\n'
                            f'Стать:{client.gender}\n'
                            f'Етап 2 - Додаткові дослідження\n'
                            f'Висновок:{ client.patientcard.prosthesis.stages_2.conclusion }')


        file_path = rf"c:\\prints\{file}.txt"
        os.system("start " + file_path)
        text_file.close()
    except:
        text_file.close()
    return HttpResponseRedirect(reverse('stage2:index', kwargs={'id': id}))

stomatology/templates/patients/add.html
{% extends 'base.html' %}
{% block title %}Визначення вартісної оцінки{% endblock %}
{% block content %}
    {% load static %}
            <form action={% url 'patients:reg'%} method='POST'>
    {% csrf_token %}
    <div class="action">

        <div>
            <h2>Картка пацієнта</h2>
        </div>
        <div class="patient-card">
            <div>
                <div>
                    <input type="text" name="last_name" placeholder="Прізвище">
                    <input type="text" name="first_name" placeholder="Ім'я">
                    <input type="text" name="middle_name" placeholder="По батькові">
                    <input type="text" name="phone" placeholder="Телефон">
                    <input type="date" name="date_birth" placeholder="Дата народження">
                </div>
                <div>
                    <label for="">Тип протезування</label>
                    <select required name="type" id="">
                        {% for type in types %}
                            {% if type.id == client.patientcard.prothesis.type.id %}
                                <option selected value={{ type.id }}>{{ type.name }}</option>
                            {% else %}
                                <option  value={{ type.id }}>{{ type.name }}</option>
                            {% endif%}
                        {% endfor %}
                    </select>
                <label for="">Конструкція</label>
                    <select required name="construction" id="">
                        {% for construction in constructions %}
                            {% if construction.id == client.patientcard.prothesis.construction.id %}
                                <option selected value={{ construction.id }}>{{ construction.name }}</option>
                            {% else %}
                                <option  value={{ construction.id }}>{{ construction.name }}</option>
                            {% endif%}
                        {% endfor %}
                    </select>
                <label for="">Матеріал</label>
                    <select required name="material" id="">
                        {% for material in materials %}
                            {% if material.id == client.patientcard.prothesis.material.id %}
                                <option selected value={{ material.id }}>{{ material.name }}</option>
                            {% else %}
                                <option  value={{ material.id }}>{{ material.name }}</option>
                            {% endif%}
                        {% endfor %}
                    </select>
                </div>

            </div>
            <div>
                <fieldset class="gender">
                    <legend>Стать</legend>
                    <div>
                        <label for="gender">М</label>
                        <input type="checkbox" id="coding" name="gender" value="М">

                    </div>
                    <div>
                        <label for="gender">Ж</label>
                        <input type="checkbox" id="music" name="gender" value="Ж">
                    </div>
                </fieldset>
            </div>
        </div>
    </div>
    <button type="submit">Save</button>
    </form>
{% endblock %}

stomatology/templates/patients/index.html
{% extends 'base.html' %}
{% block title %}Визначення вартісної оцінки{% endblock %}
{% block content %}
    {% load static %}
    <h2>Пацієнти</h2>
    <table>
        <thead>
        <th>№</th>
        <th>ПІБ</th>
        <th>Телефон</th>
        <th>Дата народження</th>
        <th>Тип протезу</th>
        <th>Етап 1</th>
        <th>Етап 2</th>
        <th>Етап 3</th>
        <th>Етап 4</th>
        <th>Статус</th>
        <th><a href={% url 'patients:add'%}>Додати</a></th>
        </thead>
        <tbody>
        {% for client in clients %}
            <tr>
            <td>{{ client.id }}</td>
            <td><a href={% url 'card:index' client.id %}>
                        {{ client.fio }}
                </a></td>
            <td>{{ client.phone }}</td>
            <td>{{ client.date_birth }}</td>
            <td>{{ client.patientcard.prosthesis.type.name }}</td>
            <td>
                <a href={% url 'stage1:index' client.id %}>
                    {% if client.patientcard.prosthesis.stages_1.date_record %}
                        {{ client.patientcard.prosthesis.stages_1.date_record }}
                    {% else %}
                        Перейти
                    {% endif %}
                </a></td>
            <td>
                <a href={% url 'stage2:index' client.id %}>
                    {% if client.patientcard.prosthesis.stages_2.date_record %}
                        {{ client.patientcard.prosthesis.stages_2.date_record }}
                    {% else %}
                        Перейти
                    {% endif %}
                </a>
            </td>
            <td>
                <a href={% url 'stage3:index' client.id %}>
                    {% if client.patientcard.prosthesis.stages_3.date_record %}
                        {{ client.patientcard.prosthesis.stages_3.date_record }}
                    {% else %}
                        Перейти
                    {% endif %}
                </a></td>
            <td>
                <a href={% url 'stage4:index' client.id %}>
                    {% if client.patientcard.prosthesis.stages_4.date_record %}
                        {{ client.patientcard.prosthesis.stages_4.date_record }}
                    {% else %}
                        Перейти
                    {% endif %}
                </a></td>
            <td>{{ client.patientcard.status }}</td>
            <td><a href={% url 'patients:delete' client.id%}>Видалити</a></td>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}